# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  TMP_DIR: $(Build.ArtifactStagingDirectory)
  WORK_DIR: $(Build.Repository.LocalPath)
  REPORT_DIR: $(Build.ArtifactStagingDirectory)/katalon-report
  VERSION: 7.7.2

steps:
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'github.com_huynguyen2908'
    userRepository: 'katalon-studio/katalon-studio'
    defaultVersionType: 'latest'
    itemPattern: 'Katalon_Studio_Engine_Windows_64-*.zip'
    downloadPath: '$(TMP_DIR)'
  displayName: Download KRE

- bash: |
    set -xe
    cd ${TMP_DIR}
    unzip Katalon_Studio_Engine_Windows_64-${VERSION}.zip
  displayName: Extract KRE

- bash: |
    set -xe
    cd ${WORK_DIR}
    ls -a
  displayName: List Files in Directory

- bash: |
    set -x
    mkdir "${REPORT_DIR}"
    katalonc="${TMP_DIR}/Katalon_Studio_Engine_Windows_64-${VERSION}/katalonc"
    "$katalonc" -noSplash -runMode=console -retry=0 -apiKey="f3238a54-e902-4dd0-8122-c15933ffad19" -projectPath="${WORK_DIR}/web-samples.prj" -reportFolder="${REPORT_DIR}" -testSuitePath="Test Suites/WebUI Builtin Keywords Test" -executionProfile="default" -browserType="Chrome" --config -webui.autoUpdateDrivers=true
  displayName: Run Web UI Test
  condition: always()
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/JUnit_Report.xml'
    searchFolder: '$(REPORT_DIR)'
    testRunTitle: 'Run Web UI tests'
